name = "GleasonFinite"
version = "0.1.0"
defaultTargets = ["GleasonFinite", "Challenge", "Solution"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "5e0c4e5239cb0a2d86d68a884bf52cfd963fce22"

[[lean_lib]]
name = "GleasonFinite"

[[lean_lib]]
name = "Challenge"
roots = ["Challenge"]

[[lean_lib]]
name = "Solution"
roots = ["Solution"]
